RUBYJS_GEN=../../rubyjs_gen
OPTS=--opt NoMethodMissing --opt NoArgumentArityChecks --opt OptimizeArithOps 
#--opt PrettyPrint
PLATFORM=--platform Konqueror

all:
	$(RUBYJS_GEN) ${OPTS} ${PLATFORM} --main HelloWorld hw.rb > hw.js
